version: "2"

plugins:
  duplication:
    enabled: true

  csslint:
    enabled: true

  eslint:
    enabled: true

  fixme:
    enabled: true

  nodesecurity:
    enabled: true

  markdownlint:
    enabled: true

  shellcheck:
    enabled: true

  editorconfig:
    enabled: true
    channel: beta

exclude_patterns:
  - node_modules/**
