if: tag IS blank

language: node_js

services: docker

node_js:
  - 9
  - 8
  - 6

cache:
  directories:
    - node_modules

stages:
  - test
  - release

jobs:
  include:
    - stage: release
      node: 9
      install: npm install --production
      script: npx semantic-release
      if: branch = master
      if: type IN (push)
